#!/usr/bin/env python

import os.path as path
from os import symlink
from subprocess import call

def get_files(f):
    for line in f:
        l=line.strip()
        if l.startswith("#") or len(l) is 0: continue
        yield l.rstrip()

dn = path.dirname(path.abspath(__file__))

def names(fn):
    names = dn, path.expanduser("~")
    return (path.join(i,fn) for i in names)

def make_link(fn):
    fn = tuple(names(fn))
    print " -> ".join(fn)
    call("rm -rf "+fn[1], shell=True)
    symlink(*fn)

ls = path.join(dn, "managed-dotfiles")
with open(ls, "r") as f:
    files = get_files(f)
    map(make_link, files)
