#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
# Pyenv seems to have a hard time with tmux on Macs..
# https://apple.stackexchange.com/questions/248813/tmux-always-modify-my-zsh-path
# system-wide environment settings for zsh(1)
export PATH=""
if [ -f /etc/zprofile ]; then
  source /etc/zprofile
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $path
  .
)

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

if [[ "$OSTYPE" == 'Darwin' ]]; then
  # Use GUI vim but don't fork shell
  alias mvim='mvim -o'
  export EDITOR='mvim -v'
else
  export EDITOR='vim'
fi

export VISUAL=$EDITOR
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi


#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$LOGNAME"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"

_local="${ZDOTDIR:-$HOME}/.zprofile.local"
if [ -f $_local ]; then
  source $_local
fi

# Setup environment. We always source this from Zshenv for non-login shells
# so we can make sure that things work the same.