#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
echo ""
if (($SHLVL == 1 )); then
  if [[ $(uname) == 'Linux' ]]; then
    neofetch --image "$HOME/Environment/startup-image.jpg"
  fi

  if [[ $(uname) == 'Darwin' ]]; then
    neofetch neofetch --ascii "$HOME/.zsh-prompt-theme/mac-ascii-art.txt"
  fi
fi


autoload -U zmv
# Use vim key bindings
bindkey -v

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Don’t clear the screen after quitting a manual page
export MANPAGER="less -X";

# Always enable colored `grep` output
export GREP_OPTIONS="--color=auto";

# Environment setup
export DESK_DESKS_DIR="$HOME/Environment/desks"

alias wow='git status'
alias such='git add'
alias very='git commit -m'
alias text-changes='git diff --color-words'
alias grr='git graph'

alias du='du -h'

export PIP_RESPECT_VIRTUALENV=true

function killport () {
  kill -9 `lsof -t -i :$1`
}

function pyview() {
  mvim -R `python -c "import os, $1; print os.path.dirname($1.__file__)"`
}

function diff() {
  git diff --color=always $1 $2 | less -r
}

# Add a newline before commands
precmd() { print "" }

_local="${ZDOTDIR:-$HOME}/.zshrc.local"
if [ -s $_local ]; then
  source $_local
fi

# Desk environment setup
[ -n "$DESK_ENV" ] && source "$DESK_ENV" || true

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
