# Install command-line tools using Homebrew
# Usage: `brew bundle Brewfile`

# Make sure we’re using the latest Homebrew
update

# Upgrade any already-installed formulae
upgrade

tap homebrew/dupes
tap osgeo/osgeo4mac

install caskroom/cask/brew-cask
cask install xquartz


# Install GNU core utilities (those that come with OS X are outdated)
# Don’t forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
install coreutils
# Install some other useful utilities like `sponge`
install moreutils
# Install GNU `find`, `locate`, `updatedb`, and `xargs`, `g`-prefixed
install findutils
# Install GNU `sed`, overwriting the built-in `sed`
install gnu-sed --default-names

# Install wget with IRI support
install wget --enable-iri

# Install more recent versions of some OS X tools
install vim --override-system-vi
install homebrew/dupes/grep
install homebrew/dupes/screen
install homebrew/php/php55 --with-gmp

# Install other useful binaries
install ack
install bfg # A git repository cleaner
install foremost # Helps with file recovery
install git
install imagemagick --with-webp
install nmap # Explores the nework
install node # This installs `npm` too using the recommended installation method
install p7zip
install pigz # Multiprocessor gzip
install pv # Monitors progress of data through a pipe
install rename # Renames files
install tree
install webkit2png
install xpdf
install zopfli # Super-performant zlib compressor
install z

install librsvg
install sleepwatcher

install pyqt --with-python3
install postgresql
install gdal --with-postgresql --with-opencl --with-unsupported --with-complete --with-python3

# Remove outdated versions from the cellar
cleanup
